version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: blog_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - blog_network

  frontend:
    build:
      context: ./frontend
    container_name: blog_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - blog_network

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
